### ISSUE TITLE
Where is groundcontrol.ini?

### ISSUE THREAD

**Issue by kevinwinsor** [WebControlCNC/WebControl#100]
Webcontrol setup says to import groundcontrol.ini. This dummy can't find it! Where do I look?

**Comment by idougal** [comment]
C:\Users\[yourusername]

**Comment by madgrizzle** [comment]
This is only if you are migrating from using ground control to webcontrol.

**Comment by kevinwinsor** [comment]
> This is only if you are migrating from using ground control to webcontrol.

I was using GC. I've tried to search but it isn't found. Is it in a particular folder?

**Comment by madgrizzle** [comment]
C:\users\\[whatever your username is]

So if your Windows user name is kwinsor, go to:

C:\users\kwinsor

.. this assumes you are using Windows.

**Comment by madgrizzle** [comment]
Closed due to lack of activity
