### ISSUE TITLE
half working after adjusting Z axis

### ISSUE THREAD

**Issue by MFD72919** [WebControlCNC/WebControl#124]
So I am pretty new to this whole thing.

Was having some issues getting my maker made to cut to the proper depth. Prior to clicking and changing the Z axis button everything was working great and i was very pleased.

after clicking that and changing the value i can no longer access any buttons. i can drop down the menu for Gcode but non of the buttons work. i click the action button and nothing happens. i can drop down the settings button but nothing in there works.

I can still move the machine with the arrow keys so its still connected.

any ideas how i can resolve this? is this something i did or a computer issue.... PLEASE HELP

**Comment by madgrizzle** [comment]
Which version are you using?  make sure you are using 0.932

**Comment by MFD72919** [comment]
.932

i even uninstalled then reinstalled just to be sure. same problem still idk why....

it was running fine all day for me

**Comment by madgrizzle** [comment]
hmm.. when you see behave like that, it means some crashed.  can you repeat it and screenshot the messages in the terminal window that's running it?  Is this windows, linux, or raspberry pi version?

**Comment by MFD72919** [comment]
it is windows. and i cant do anything with it now in turms of messages. i cant upload gcode. or click any buttons. the only buttons that work are the arrow keys to move the sled and the home button (which doesnt actually send it home but does move the motors)

**Comment by madgrizzle** [comment]
can you screenshot the terminal window that its running in?  I want to see if there are any error messages.  When you click it to start, a terminal window opens up and the browser launches.

**Comment by MFD72919** [comment]
![thumbnail](https://user-images.githubusercontent.com/63759136/79408952-3d49f100-7f62-11ea-8082-5a0016343ba5.jpeg)
![thumbnail (1)](https://user-images.githubusercontent.com/63759136/79408957-420ea500-7f62-11ea-9f4c-e7453564064d.jpeg)

**Comment by madgrizzle** [comment]
And when you click Actions, does anything appear on the terminal window?

**Comment by MFD72919** [comment]
9cf6895a0634f9db476b5f58b2988

**Comment by MFD72919** [comment]
then it just popped up client discounnected. getting photo now

**Comment by madgrizzle** [comment]
That's normal.  But the action menu doesn't come up?

**Comment by MFD72919** [comment]
![IMG_20200415_215040](https://user-images.githubusercontent.com/63759136/79409364-63bc5c00-7f63-11ea-9b5f-67fd970ded7b.jpg)

**Comment by MFD72919** [comment]
nothing opens. even if i go into settings or gcode the menu drops down but when you click anything nothing happens

**Comment by madgrizzle** [comment]
have you tried restarting the browser?  Maybe force refresh (Ctrl-F5) I've not seen this behavior before.  You're running Edge?

**Comment by MFD72919** [comment]
yes edge. it was running flawlessly all day was super happy with it. i will try the refresh now

**Comment by madgrizzle** [comment]
>after clicking that and changing the value i can no longer access any buttons.

What value did you change?  And to what did you change it to?

**Comment by MFD72919** [comment]
no change after refresh except it says not connected but i can still move the sled with the arrows

and z axis said .1 and i was trying to change it to .5.

**Comment by madgrizzle** [comment]
scroll up on that terminal screen to where it starts and see if there are any messages at the beginning.. something about error or something.

**Comment by MFD72919** [comment]
nothing different than what i sent before

**Comment by madgrizzle** [comment]
Try reaching it via 192.168.1.3:5000 instead of localhost:5000.  I'm sort of grasping at straws here.  Have you rebooted the computer?

**Comment by MFD72919** [comment]
yep i restarted it after i did a reinstall. i may try and wipe it out again tomorrow and reloading it all over. i just dont know what i did to cause this to happen kind of frustrating because it was working so well... for what its worth the calibration process went crazy smooth

**Comment by madgrizzle** [comment]
Hit Ctrl-Shift-I in the browser and it will bring up a debugger screen.  Then click the 'console' tab on the debugger.. you should see a bunch of messages.  Click actions and screenshot it.  This is what mine looks like after pressing Actions
![image](https://user-images.githubusercontent.com/5055291/79410407-53f64500-7f6e-11ea-8b02-42441a02b664.png)

**Comment by MFD72919** [comment]
bunch of errors stand by

**Comment by MFD72919** [comment]
![IMG_20200415_221329](https://user-images.githubusercontent.com/63759136/79410568-6a989e00-7f66-11ea-97f5-228895c8ef83.jpg)
![IMG_20200415_221345](https://user-images.githubusercontent.com/63759136/79410573-6d938e80-7f66-11ea-93f1-84a1d231d672.jpg)

**Comment by madgrizzle** [comment]
Well, that's the problem but I have no clue what's causing it specifically.  I'm THINKING that there is a some setting that is wrong and its having a problem with it.  Can you email me the webcontrol.json file.. send to madgrizzle maslow at gmail dot com.  You can find the file in C:\users\azide\.WebControl

Note there's a period in front of WebControl

**Comment by madgrizzle** [comment]
madgrizzlemaslow at gmail dot com

**Comment by MFD72919** [comment]
sent

**Comment by madgrizzle** [comment]
Ok, I was right... good!  Open that file with a text editor (notepad is fine) and search for the word NaN.  It stands for 'Not A Number' (computer thing).  You should find it under the 'distToMoveZ' entry.  Change that from NaN to 0.5 and save it.

**Comment by madgrizzle** [comment]
Something glitched when you changed it.  I can't readily duplicate it, so its hard to tell.

**Comment by madgrizzle** [comment]
Its near midnight here.  I'm fairly confident that will fix your problem.. I'll check back in the morning.

**Comment by MFD72919** [comment]
it wont open at all now lol dialog box opens then closes... i just deleted it off my harddrive going to redownload....

**Comment by madgrizzle** [comment]
Let me send you a corrected file to replace the one.  I'll reply to your email.

**Comment by madgrizzle** [comment]
Redownloading won't help.  Try the one I just sent.

**Comment by MFD72919** [comment]
all good now the reload. thank you!!
