### ISSUE TITLE
Discussion: Vision for the Future of WebControl

### ISSUE THREAD

**Issue by madgrizzle** [WebControlCNC/WebControl#156]
@WebControlCNC/maintainers , @WebControlCNC/developers 
I'd like to have a discussion on the "vision for the future of webcontrol" but rather it seems that doing so in the "issues" isn't really appropriate.  Is there a better way to do so?  It's not just for the application, but also the firmware, so its more of a WebControlCNC kind of discussion.

**Comment by davidelang** [comment]
do it on the forum

David Lang

**Comment by madgrizzle** [comment]
I created a discussion in the teams section where there's been a bunch of discussion.  Ive invited you a few times to join the org, but it's still pending.  I tried the email address again, so hopefully that will work.

**Comment by zaneclaes** [comment]
Relevant:
https://forums.maslowcnc.com/t/documenting-maslow-what-am-i-missing/13537/2
