### ISSUE TITLE
gcode stops running randomly; last logs are "5.08,WPos:0.000,0.000,0.000>"

### ISSUE THREAD

**Issue by zaneclaes** [WebControlCNC/WebControl#159]
I originally configured my Maslow with GroundControl and then imported my settings to WebControl. I've tried two cuts with WebControl, both of which stopped within the first few minutes. By "stopped," I mean that the all motors ceased operation and the sled has now remained still for over 10 minutes. 

The last logs look like this:

```
Sending: G1 X-22.4770 Y-16.15840  
Sending: G1 X-22.3940000000000019 Y-16.23840  
Sending: G1 X-22.3120 Y-16.31910

5.08,WPos:0.000,0.000,0.000>
5.08,WPos:0.000,0.000,0.000>
5.08,WPos:0.000,0.000,0.000>
5.08,WPos:0.000,0.000,0.000>
```

I've tried to pause-then-play, but that did not resume anything. I'd prefer to salvage this board if possible, so I'm nervous to try anything else.

@madgrizzle any thoughts?

**Comment by madgrizzle** [comment]
The logs seem weird because its cutoff.  Are you able to go to Actions->Download Diagnostircs File and send to madgrizzlemaslow at gmail dot com?

**Comment by madgrizzle** [comment]
and email the gcode as well?

**Comment by zaneclaes** [comment]
Whoops, forgot to mention — no I am not. The `downloadDiagnostics` page times out.

I suspect that the CPU is over-taxed. The top says it's using 75-90% of the CPU. I'm running a Raspberry Pi 3B+ with a 7" touchscreen display and camera (all official RPi hardware).

I also just noticed that on a larger webbrowser I can see logs that exist between the two groups:
```
G1 X-20.02890 Y-21.010
PCB v1.2 Detected
Grbl v1.00
ready
position loaded at:
-493.97
-533.72

5.08,WPos:0.000,0.000,0.000>
5.08,WPos:0.000,0.000,0.000>
5.08,WPos:0.000,0.000,0.000>
5.08,WPos:0.000,0.000,0.000>
>
5.08,WPos:0.000,0.000,0.000>
```

Seems like maybe the USB somehow re-connected ..?

**Comment by zaneclaes** [comment]
I'm going to try swapping it out for a RPi4 instead of RPi3B+, which has a much better CPU. Here's the CPU usage monitored by Prometheus on a RPi3B+:
<img width="1424" alt="Screen Shot 2020-05-29 at 9 54 07 AM" src="https://user-images.githubusercontent.com/2084821/83279497-69c47000-a192-11ea-91c0-84203c515ffb.png">

**Comment by madgrizzle** [comment]
I'm concerned about the cut-off logs.. the last lines with 5.08, WPos:0.00...> should look like <MPos: xxx.xx, xxx..xx, 5.08, WPos:0.00 ...>

I wonder if there was a serial hiccup and part of webcontrol crashed because of malformed log data.

**Comment by madgrizzle** [comment]
I would be hesitant about running the gui/browser concurrent with webcontrol on an RPI 3B+.  Not sure what load the camera would put on.  Are you using the camera feature of webcontrol or something else.. because webcontrol's camera feature is taxing as well.

**Comment by madgrizzle** [comment]
Reset your chains (sled might have lost position if there was a usb-disconnect) and then skip ahead using the > buttons (or use the goto) to the line where it stopped working and hit play.  If it works as intended, you should be able to pickup from where it left off.

**Comment by zaneclaes** [comment]
> I wonder if there was a serial hiccup and part of webcontrol crashed because of malformed log data.

That seems plausible. I hope it's not hardware related; I have the USB cable running along the ceiling to the Maslow from the control unit.

> I would be hesitant about running the gui/browser concurrent with webcontrol on an RPI 3B+. Not sure what load the camera would put on. Are you using the camera feature of webcontrol or something else.. because webcontrol's camera feature is taxing as well.

Fair enough. I did try letting the display go blank (less CPU) and turning the camera off.

**Comment by zaneclaes** [comment]
Okay, definitely a CPU issue. RPi4 fixed this bigly. ~33% CPU usage now. This is my first home-grown gcode cut (used Easel to convert SVG).
<img width="1677" alt="Screen Shot 2020-05-29 at 10 43 11 AM" src="https://user-images.githubusercontent.com/2084821/83284339-c6775900-a199-11ea-8864-5d58d67b6ea8.png">

**Comment by zaneclaes** [comment]
Shoot... I have to re-open this. Looks like the Pi4 delayed the onset of the problem, but did not fix it. It takes ~1 hour of cutting to get to a disconnect, now. I actually think the whole container may be getting killed. The server becomes unresponsive for a couple minutes and then then gcode is not loaded any more. It may also be a networking issue, given that my garage is on the border of wifi range. I'm trying to narrow down symptoms now...

I will likely just switch to a headless RPi, though, and remove the external monitor. My phone works fine, now that I think about it ;)

**Comment by madgrizzle** [comment]
Can you send me the gcode.. to make sure it isn't failing on something in it?

**Comment by madgrizzle** [comment]
I looked at the gcode and it seems tame (easel gcode is what I used when I first started working on webcontrol).  I tend to think something is hiccuping the serial connection.  Either there's a RPI issue with a lot of things running (possibly camera) or there's a USB connection issue.  If data coming from the arduino gets corrupted, its possible that some of the parsing fails and causes one of the threads to crash, but I try to catch those situations so I don't really know.  If you can email me your log.txt file from the .WebControl folder, that might tell us what caused it to crash.

**Comment by zaneclaes** [comment]
Sent! On the most recent stop, I actually did get a dialog that the USB had disconnected. And I haven't seen the Docker container actually definitively crash, so it may be that...

**Comment by madgrizzle** [comment]
I'll look at log later tonight or in the morning.  How long of a USB cable is between the rpi and the Arduino?

**Comment by zaneclaes** [comment]
It's the long blue cable that comes with the Maslow Classic kit. I want to say ~15ft.

**Comment by zaneclaes** [comment]
Just briefly looking at `alog.txt`, this suspicious block seems to appear before many of the restarts. I don't believe there's any actual chain-over-sprocket error...
```
19.49: $32=1.00000000 (z axis Pos proportional weight)
19.51: $33=5.00000000 (z axis Kp Velocity)
19.52: $34=0.00000000 (z axis Ki Velocity)
19.54: $35=0.27999999 (z axis Kd Velocity)
19.56: $36=1.00000000 (z axis Velocity proportional weight)
19.58: $37=81.73586273 (chain sag correction value)
19.64: $38=2 (chain over sprocket)
19.66: $39=3 (PWM frequency value 1=39,000Hz, 2=4,100Hz, 3=490Hz)
19.68: $40=0.00000000 (chain tolerance, left chain, mm)
19.74: $41=0.00000000 (chain tolerance, right chain, mm)
19.76: $42=2.00000000 (position error alarm limit, mm)
19.77: ok
```

**Comment by madgrizzle** [comment]
That looks like just the settings being reported by the controller.. this happens after a restart so webcontrol can sync up the controller and send any setting updates that are needed.

**Comment by madgrizzle** [comment]
15 foot cable might the source of the problem.  Some people have had issues with even shorter cables.

**Comment by madgrizzle** [comment]
If you sent the log, I didn't receive it.

**Comment by Orob-Maslow** [comment]
@zaneclaes I use a 1' cable on a headless rpi3 (with external start/stop buttons) and the once I had a problem similar to your description when I turned on the "buffer gcode" option in webcontrol settings.  It defaults to "off," so it likely is not your issue, but you might look at that setting to verify.

**Comment by zaneclaes** [comment]
> If you sent the log, I didn't receive it.

Sorry, got stuck in the upload; one of them was 3Mb.

> I turned on the "buffer gcode" option in webcontrol settings. It defaults to "off," so it likely is not your issue, but you might look at that setting to verify.

Thanks for the tip; confirmed that it's off.

I'd prefer to drive the camera with the same RPi that drives the Maslow, for cost saving purposes. However, I do have a super-long camera cable, so perhaps I can move the Pi to the back of the frame and switch to a shorter USB...

However, I should mention that GroundControl worked fine on my laptop with this same USB cable. I had a 4 hour cut that went perfectly before I switched to WebControl.

Furthermore, the fact that switching to a faster CPU **improved** the problem would generally hint at a problem on the Pi and/or WebControl side of things. A better CPU should not make a broken USB cable better, unless there are in fact two problems happening here concurrently...

**Comment by zaneclaes** [comment]
In further debugging, I've found a few bugs...

WebControl always reports CPU usage of 10-40% range. However, Kubernetes is able to inspect the container usage with greater precision, and finds that this value is inaccurate. This would not be surprising if WebControl had _overestimated_ the usage, because it may have been constrained to the containers' definition of maximum CPU/RAM, but the fact that it's _underestimating_ usage suggests a bug:
<img width="1412" alt="Screen Shot 2020-05-30 at 7 57 56 AM" src="https://user-images.githubusercontent.com/2084821/83330418-f41cda80-a24b-11ea-8974-eb61bfd553c8.png">

Note that the CPU dropped precipitously after I turned the camera off near the end. This is expected of course, but what caught my attention is the network utilization. WebControl was sending ~10Mbps and receiving ~5Mbps. That's more than Netflix. 

As an experiment, I turned off the camera and instead loaded up MotionEye (a piece of software meant for turning RPis into webcams). I set it to stream 1080p resolution at 30FPS and let it run in one browser, and WebControl (with the camera off) in another browser. Now the total CPU utilization (MotionEye+WebControl) is roughly 25% of the total CPU, whereas WebControl with the camera was running at 50-60% of the total CPU. Also note that the network utilization is down to ~900 Kbps (less than 10% of what WebControl required to stream the video):
<img width="2945" alt="Screen Shot 2020-05-30 at 8 19 09 AM" src="https://user-images.githubusercontent.com/2084821/83330722-6d1d3180-a24e-11ea-9ec0-69ee13a6c33f.png">
The CPU spike happens when I load the WebControl UI via a browser, so this further points at massive inefficiencies in the socketIO connection. 

Finally, there appears to be a memory leak. We should not see these step increases in the memory utilization of the container. They seem coupled to usage of the web interface (note how it was constant at night, before I woke up):
<img width="1420" alt="Screen Shot 2020-05-30 at 8 01 14 AM" src="https://user-images.githubusercontent.com/2084821/83330502-8e7d1e00-a24c-11ea-8509-8c7bb7bc9d2e.png">

If there are memory leaks within the socket IO (easy to do), WebControl will inevitably crash on machines like this (RPi4 with only 1GB RAM).

**Comment by zaneclaes** [comment]
Okay, I've now cut 1.5 sheets of plywood using MotionEye for the camera without any crashes. As long as the camera is off, opening additional browser windows on other computers etc. does not cause any negative long-term performance issues. I think it's safe to close this now, unless we decide to invest in WebControl over CNCjs (in which case this foot-gun should be dealt with).

@emilecantin just FYI I have easy ways to benchmark my cluster like in the above screenshots (if you want me to do so for CNCjs).
