### ISSUE TITLE
Stop using buttons for indicators

### ISSUE THREAD

**Issue by madgrizzle** [WebControlCNC/WebControl#17]
Find a better way to show indicators because using buttons is lazy when they aren't supposed to be pressed.

**Comment by pennltrex** [comment]
use a div with the class="alert alert-success" and "alert alert-danger" instead.

**Comment by madgrizzle** [comment]
This has been done (for webcontrol).  Should be in next update.

**Comment by madgrizzle** [comment]
no more buttons for indicators.
