### ISSUE TITLE
Ubuntu 21.04 Update & WebControl

### ISSUE THREAD

**Issue by erik-vroom** [WebControlCNC/WebControl#186]
The screen that comes up for WebControl after update is a listing of options rather than the normal graphic, see screenshot.  Clicking on a hyperlink does nothing. I'm not sure if the issue is with Chromium or Ubuntu or is a user error.
![Screenshot from 2021-08-28 07-02-32](https://user-images.githubusercontent.com/76229080/131216123-d25e3901-3e19-45b8-997d-f7db8963eb9c.png)

**Comment by gb0101010101** [comment]
This looks like a browser cache issue. Try reloading the page with hard refresh using [CTRL] + [F5] keys.

**Comment by erik-vroom** [comment]
It seems to be working now, thanks for the help.
