### ISSUE TITLE
Feature Request: Ability to send arbitrary gcode

### ISSUE THREAD

**Issue by madgrizzle** [WebControlCNC/WebControl#21]
Add a screen that allows users to enter gcode and send it, line by line, sequentially.

**Comment by davidelang** [comment]
start off with the very simple ability to do something like:

webcontrol/gcode?g0 X0 Y0 G1 Z-5

etc

**Comment by madgrizzle** [comment]
I've added a web page to type in and send gcode.

**Comment by davidelang** [comment]
this is not working on 0.918

**Comment by blurfl** [comment]
Pasting 

```
g0 X0 Y0 G1 Z-5
```
into the 'Send Custom Gcode' form works as expected in 0.918 on a pi-singledirectory installation.

**Comment by davidelang** [comment]
10.0.10.50:5000 gets me to webcontrol 10.0.100.50:5000/gcode gets me an 'unknown url' error

**Comment by madgrizzle** [comment]
webcontrol uses websockets for the most part so the /gcode isn't something that's routed.  By selecting GCode from the menu and pressing 'Send Custom GCode' it will request the page and should show it in a modal screen.

**Comment by davidelang** [comment]
ok, I missed that, from the comment I thought it was just change the url and I would get a form

**Comment by madgrizzle** [comment]
Yeah, I see how it could be read that way.

**Comment by davidelang** [comment]
having the ability to do something like I was reading it would make it really 
easy to hook in other controls.

David Lang

On Sat, 14 Dec 2019, madgrizzle wrote:

> Yeah, I see how it could be read that way.
ëë>
>
