### ISSUE TITLE
Bundle Test

### ISSUE THREAD

**Issue by BarbourSmith** [WebControlCNC/WebControl#26]
I am super excited about the windows bundled version of Web Ground Control. Phenomenal. I had no issues at all starting up the bundle on my computer (Windows 10 ), but once the program was launched it wasn't clear to me how to visit the generated webpage. Would it be possible to add a shortcut in the folder, or even better spawn the browser automatically when the program launches?

**Comment by davidelang** [comment]
the shortcut would depend on what browser you have installed :-)

open a browser and go to localhost:port (I think port is 8000, but I don't 
remember offhand)

David Lang

**Comment by blurfl** [comment]
WebControl is bound to port 5000, so to reach it, browse to http://xxx.xxx.xxx.xxx:5000.

**Comment by blurfl** [comment]
Another approach would be for the .exe to print the address:port in its window when it has connected to the Mega. Users will want to connect from other devices as well.

**Comment by BarbourSmith** [comment]
We should be able to make a shortcut like this which opens in the user's default browser. 

[shortcut.zip](https://github.com/madgrizzle/WebControl/files/3608594/shortcut.zip)

I agree with @blurfl that a print statement telling folks how to connect from a phone or other device could be nice too.

**Comment by madgrizzle** [comment]
It looks like python can open a browser window with two lines of code:
>import webbrowser
>webbrowser.open_new_tab("http://localhost;5000")

I don't know the effect of that code when you have a headless system (like an RPI), but suspect its mostly harmless.  I'll test it tonight.

**Comment by madgrizzle** [comment]
How about reporting the ip address and port information up in the navbar?  Instead of the alert saying "Connected", it can report the IP:Port as well.

![image](https://user-images.githubusercontent.com/5055291/64867043-96d3f100-d60a-11e9-88fa-9ddb3c6c1b68.png)

**Comment by BarbourSmith** [comment]
Awesome! Way to find the ideal solution in less than a day 😁

I like the connection status idea as long as there is room for it

**Comment by madgrizzle** [comment]
There's plenty of room for it on the desktop browser.. It won't appear on the mobile device, but the mobile device never showed "Connected".. just an icon and I think if you are on a mobile device talking to webcontrol, you probably already figured out the IP address.

**Comment by BarbourSmith** [comment]
Fantastic! I'm going to close this

**Comment by madgrizzle** [comment]
I've determined this solution doesn't really work on the RPI.. the local address that appears is the docker container's internal IP address, which is not the same as the hosts address.  Since that's not related to "Bundle Test", I'm just going to create a new issue for it and see if I can figure it out.
