### ISSUE TITLE
IP address reported on docker-based system isn't the host's address

### ISSUE THREAD

**Issue by madgrizzle** [WebControlCNC/WebControl#34]
Long story short.. when running in a docker on an RPI, webcontrol reports the docker container's internal ip address, which is not accessible outside the RPI.

To fix, it appears the IP address has to be injected via an environmental variable.  However, WebMCP is used to start the webcontrol docker, so it needs an injection as well.. that means the startup script in the pre-built image needs to inject it.  Lot's of changes to make it work and I'm not sure how to modify everyone's startup scripts.

**Comment by BarbourSmith** [comment]
Oooch that sounds like a hassle

**Comment by madgrizzle** [comment]
For a vast majority of the cases, the rpi will be headless so you need to know the ip address to get there in the first place.  I'm not sure just how important it is to display it on the screen for this use case.

**Comment by BarbourSmith** [comment]
Yeah, it sounds like it might not really be needed to display it on the screen in the first place

**Comment by madgrizzle** [comment]
Closing this because its docker related and I don't think I'm going to be able to fix it.
