### ISSUE TITLE
webcontrol-linux pre-release

### ISSUE THREAD

**Issue by blurfl** [WebControlCNC/WebControl#36]
tested on Raspbian Stretch, error:
>./webcontrol: cannot execute binary file: Exec format error

tested on Linux Mint 19.2 in a VM, ran but G-Code, Actions, Settings, Boards actions did not appear. Sub-menus showed but nothing happens when one is selected.

**Comment by madgrizzle** [comment]
I don't know why I don't get alerted to new issues.

Anyway, the issue is related to webgl not running on a browser inside the VM, which is not an issue with webcontrol outside the fact that webcontrol uses webgl for the gcode rendering.

**Comment by BarbourSmith** [comment]
If you click the "watch" button at the top you should be alerted to new issues through email:

![image](https://user-images.githubusercontent.com/9359447/66066569-11c56300-e54a-11e9-8c19-7931351f6f37.png)

**Comment by madgrizzle** [comment]
I have it set to watch.. maybe I missed it or it ended in spam. /shrug
