### ISSUE TITLE
WebControl G2 Z axis rendering issues

### ISSUE THREAD

**Issue by blurfl** [WebControlCNC/WebControl#5]
I'm not certain where the error is, but it can be seen by comparing the way that WebControl renders this code:

```
G20 G90
G0 X0 Y0 Z0
G2 X.0 Y0.001 Z-0.25 I-1.0 J0.0 F100
G2 X.0 Y0.001 Z-0.50 I-1.0 J0.0 F100
G2 X.0 Y0.001 Z-0.75 I-1.0 J0.0 F100
G0 X0 Y0
G3 X.0 Y0.001 Z-0.50 I1.0 J0.0 F100
G3 X.0 Y0.001 Z-0.25 I1.0 J0.0 F100
G3 X.0 Y0.001 Z00.00 I1.0 J0.0 F100
G0 X0 Y0 Z0
M2
```

![screen shot 2018-11-24 at 2 36 17 pm](https://user-images.githubusercontent.com/1851315/48973541-501ef700-eff6-11e8-936e-8fcd1168eaf6.jpg)

to the way it is rendered by [this](https://nraynaud.github.io/webgcode/) gcode renderer 
![screen shot 2018-11-24 at 2 31 17 pm](https://user-images.githubusercontent.com/1851315/48973509-9e7fc600-eff5-11e8-81f5-3e0a923e993d.jpg)

**Comment by madgrizzle** [comment]
Thanks.. I'll look into it.

⁣Sent from BlueMail ​

**Comment by madgrizzle** [comment]
I think it's fixed now.  Needed to fix the way z-axis steps were incremented.. let me know.
![image](https://user-images.githubusercontent.com/5055291/48974821-6a29fb00-f031-11e8-861e-6b3ac0d7a5fb.png)

**Comment by blurfl** [comment]
The image looks correct - screwing down on one side, up on the other.

**Comment by madgrizzle** [comment]
Looks fixed.
