### ISSUE TITLE
Manual Z-Axis Control don;t seem to work correctly Z-Axis Motor

### ISSUE THREAD

**Issue by idougal** [WebControlCNC/WebControl#58]
I downloaded, unzipped, and ran webcontrol-0.919-win64-singledirectory.zip.
I Upgraded to Holey Firmware 

I entered in Maslow, Advanced, and Webcontrol settings as best I could.

I ran the quick configure action.

I wanted to check the Z axis level and pressed Z-Axis in controls. When I pressed raise. the left motor turned instead of the Z-Axis.

I shut Webcontrol down and restarted.

I ran the test encoders action and all motors moved correctly.  (L, R, Z)

I went to manual control Z-Axis and pressed raise.  The Z motor makes a noise but it doesn't spin.  I tried the default raise value. 0.5mm, and 5mm,  All had the same result.  The motor makes a humming noise. but doesn't spin.

I tried testing the motors and encoders again and all three motors operated correctly.

I tried inches... same result.

I pressed Define Zero and now the motor won't make a noise or spin when I press raise or lower.

Diagnostic file attached

[wc_diagnostics_20200113-164018.zip](https://github.com/madgrizzle/WebControl/files/4056586/wc_diagnostics_20200113-164018.zip)

**Comment by idougal** [comment]
The problem seems to have disappeared after I ran the Set sprockets and reset chain procedure

**Comment by madgrizzle** [comment]
Closing..
