### ISSUE TITLE
Stop button in Triangular configuration doesn't work

### ISSUE THREAD

**Issue by idougal** [WebControlCNC/WebControl#59]
I was running a triangular calibration and had to restart for a couple of external problems.  I pressed the Stop button in the triangular control and received this message "Function not currently implemented.  Sorry [StopCut]"

Thankfully these weren't time sensitive emergencies and I was able to leave the window and stop the test in the manual menu.

**Comment by madgrizzle** [comment]
Wow, thanks for the find.

**Comment by madgrizzle** [comment]
This should be fixed.. I'll close.
