### ISSUE TITLE
Webcontrol Holey Calibration Accept Results button doesn't appear to do anything

### ISSUE THREAD

**Issue by idougal** [WebControlCNC/WebControl#71]
webcontrol-0.920-win64-singlefile.zip

- I pressed the "Upgrade Holey Firmware:51.27 button.
- I ran the Holey Configuration.
- I entered the measurements 
- I pressed Calculate and the calculations created the following numbers:
Motor Height = 1044.66923
Motor Distance 3674.95128
Left Chain Tol = -0.21402
Right Chain Tol = -0.18505
Cal Error: 2.353674533147113
- I pressed accept results
I went back to Settings/Maslow Settings and the following results are listed

Distance  = 3719.6
Motor Height = 1056.3

Then I went to Settings / Advanced settings and the following results are listed:

Chain Tol Left = 0
Chain Tol Right = 0

Shouldn't these number change when I press accept results?

**Comment by madgrizzle** [comment]
Gives you a lot not confidence, huh?  I look at it in the morning.. something is up for certain.

**Comment by madgrizzle** [comment]
Yep, didn't do anything.  Problem was that I moved the accept button to be on the same line as the calculate button.  That put the button within the form and therefore, for whatever reason, the javascript on-click code doesn't run (any idea why?).  I must have forgotten about that when I made the change (made the change so people readily see the accept button).  So I moved the button back to where it was (at the very bottom) and it works now.  I'll make a new release today/tonight with this change and the ui changes incorporated.

**Comment by madgrizzle** [comment]
Let me know if this fixed it so it can be closed.  Thanks.

**Comment by idougal** [comment]
It did work in 922, but the calculated numbers were slightly different


Pre 922 | 922.00000
-- | --
Between motors 3677.413 | 3768.75406
Height 1044.854 | 1044.33488
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
Left Chain -0.15281 | -0.17030
Right Chain -0.17296 | -0.16872

**Comment by davidelang** [comment]
when youdo holey calibration multiple times, each time it works from the prior 
one

and it's sensitive that even a slight error in your measurement will change the 
results.

David Lang

**Comment by idougal** [comment]
I made sure all the settings were identical to my pre test settings before I ran the actual calibration previously.  Then I typed in the same measured values from that test that I had typed in before.

Shouldn't identical settings and measurements output the same calculated results?

**Comment by davidelang** [comment]
On Wed, 22 Jan 2020, idougal wrote:

> I made sure all the settings were identical to my pre test settings before I 
> ran the actual calibration previously.  Then I typed in the same measured 
> values from that test that I had typed in before.
>
> Shouldn't identical settings and measurements output the same calculated 
> results?

including identical calibration values for each run?

there is an ability to backup your json settings file and restore it, that's the 
only way to be very sure that you are at the same starting point.

David Lang

**Comment by madgrizzle** [comment]
If you have the exact same settings as previous and enter the exact same measurements, you should get the exact same result.  I tested this by pressing calculate two times and the values didn't change the second time around.  But, even a slight change in setting could yield different optimized values.  I will say that I made no change in 922 that would have caused different results from 921.  It was just an simple html file adjustment.

**Comment by davidelang** [comment]
On Thu, 23 Jan 2020, madgrizzle wrote:

> If you have the exact same settings as previous and enter the exact same 
> measurements, you should get the exact same result.  I tested this by pressing 
> calculate two times and the values didn't change the second time around.

right, but if you save your settings and then go back to the calibration and 
re-enter the same values, you aren't in the same starting point. (I think you 
understand this, but it's an easy trap for people to fall into)

David Lang

**Comment by madgrizzle** [comment]
I assumed he didn't save his settings because the button to accept the setting changes wasn't working... but yes, you are correct in how it does work.

**Comment by idougal** [comment]
The test settings under After test 3 were the settings in the machine before I ran my big calibration test.
![image](https://user-images.githubusercontent.com/59851975/73005739-ab00d980-3dc6-11ea-9a56-19d32f829d44.png)
I was pretty happy.  Straight lines look straight, squares look like squares, circles look like circles.  Most errors were less than 2mm and the biggest error was 5mm.

![IMG_20200123_095728](https://user-images.githubusercontent.com/59851975/73005888-f6b38300-3dc6-11ea-9f8c-a1ada8dba1b6.jpg)

Then I started testing previous tickets.  Then I was testing this ticket and went back into the settings and made sure all settings matched "before Test 3" above.  
![image](https://user-images.githubusercontent.com/59851975/73007136-33807980-3dc9-11ea-84c1-4b380f282d77.png)
![image](https://user-images.githubusercontent.com/59851975/73007157-4004d200-3dc9-11ea-8dc1-da0a9361b47b.png)

![image](https://user-images.githubusercontent.com/59851975/73006358-c0c2ce80-3dc7-11ea-8bbd-34c0d231b157.png)
![image](https://user-images.githubusercontent.com/59851975/73006395-d0daae00-3dc7-11ea-8183-5f23a1736701.png)
![image](https://user-images.githubusercontent.com/59851975/73006568-16977680-3dc8-11ea-8537-460f55026f0f.png)
![image](https://user-images.githubusercontent.com/59851975/73006583-1eefb180-3dc8-11ea-99e4-91eefe7181a5.png)
![image](https://user-images.githubusercontent.com/59851975/73006647-33cc4500-3dc8-11ea-83b3-b1f43aa251f0.png)
![image](https://user-images.githubusercontent.com/59851975/73006677-3e86da00-3dc8-11ea-8213-eb003b208157.png)
![image](https://user-images.githubusercontent.com/59851975/73006695-46467e80-3dc8-11ea-8884-9473c30da264.png)
![image](https://user-images.githubusercontent.com/59851975/73006716-5199aa00-3dc8-11ea-93ec-9eeb35bea6a9.png)

Then I pretended to run the holey calibration and entered the same measured values after Test 3 ran:
![image](https://user-images.githubusercontent.com/59851975/73007338-9e31b500-3dc9-11ea-95eb-6818b282939c.png)

![image](https://user-images.githubusercontent.com/59851975/73007297-8f4b0280-3dc9-11ea-81da-93db16df6cab.png)
![image](https://user-images.githubusercontent.com/59851975/73007401-b7d2fc80-3dc9-11ea-8d3c-f13ea01d37d0.png)
![image](https://user-images.githubusercontent.com/59851975/73007453-ce795380-3dc9-11ea-85f2-65cb90ec09f1.png)

When I click calculate, I am expecting to see the same calculated values I got when I ran the test

![image](https://user-images.githubusercontent.com/59851975/73006971-cec51f00-3dc8-11ea-86bd-bca937852668.png)

But I get these values instead

![image](https://user-images.githubusercontent.com/59851975/73007568-fbc60180-3dc9-11ea-9b7d-03b7b0e68f04.png)

I accepted them and just ran the top line of my test cut and I get a u-shape instead of the straight line I got earlier.

![IMG_20200123_095748](https://user-images.githubusercontent.com/59851975/73007636-16987600-3dca-11ea-9393-2a58746d77c1.jpg)

I tried manually putting all the settings in that I ran the test cut at and ran it again. The new line isn't quite as u-shaped, but it's not straight and nowhere near the original cut with what should be identical settings because I've manually changed them all and double checked them.

**Comment by madgrizzle** [comment]
Thanks for all the detail.  I put your numbers into my copy of webcontrol running 0.922 (matched your settings and measurements) and hit calculate and got the exact same numbers you did...

![image](https://user-images.githubusercontent.com/5055291/73009896-4b62f800-3ddf-11ea-9850-fce6261a7df6.png)

Then I did 0.921 and got the same results

![image](https://user-images.githubusercontent.com/5055291/73011121-9f6edc00-3de1-11ea-99a6-8c9cd4dbadba.png)

Then I did 0.920 and got the same results

![image](https://user-images.githubusercontent.com/5055291/73011706-c843a100-3de2-11ea-810d-69e907db2dc8.png)

I'm fairly confident nothing changed in the computations because I haven't messed with that in a long time.

**Comment by gb0101010101** [comment]
> @madgrizzle That put the button within the form and therefore, for whatever reason, the javascript on-click code doesn't run (any idea why?)

The button was probably submitting the form. You can typically stop this by adding `; return false;` to the onClick.

**Comment by madgrizzle** [comment]
Closing as I think it works now.
