### ISSUE TITLE
WebControl not opening Gcode files properly

### ISSUE THREAD

**Issue by amantalion** [WebControlCNC/WebControl#78]
Hi, has anyone had problems with their Gcode files when opening them with WebControl? It looks like my Gcode is missing some sections. Please, see the screenshot below to understand what I mean (it is supposed to be a circle within a square):

![image](https://user-images.githubusercontent.com/59008704/72768474-68fc4b80-3bac-11ea-8dc0-b3a5d892333f.png)

GroundControl is opening the Gcode file properly:

![image](https://user-images.githubusercontent.com/59008704/72768482-6c8fd280-3bac-11ea-9d5f-ec9db200cd10.png)

**Comment by madgrizzle** [comment]
Can you email the file to madgrizzlemaslow at gmail dot com?

**Comment by amantalion** [comment]
@madgrizzle Thank you for the fast reply. Just emailed you the file.

**Comment by madgrizzle** [comment]
Well, that's the first time I've seen gcode lines without a gcommand.  I guess if it's the same command as previous line, it can be left out and still be valid gcode.  I'll have to work on that, but in the meantime, if you edit the code and fill in where the G command is missing, it'll display properly.

**Comment by madgrizzle** [comment]
Are you able to view the gcode after its loaded in Ground Control and tell me if it looks different.. like if ground control added G0, G1, G2, etc. in front of the lines that didn't have them?

**Comment by madgrizzle** [comment]
Nevermind.. that helped me solve a mystery I had long forgotten about.  Simple fix.  It will be updated in the next release.  Thanks!!

**Comment by amantalion** [comment]
Great, glad that it helped! 

Yes, it looks the same in GroundControl, if I insert G commands from previous lines. Also, the problem was fixed in WebControl after I added those missing G commands.

**Comment by amantalion** [comment]
@madgrizzle Also, do you know when the next release will be out approximately?

**Comment by madgrizzle** [comment]
Probably tomorrow.
