### ISSUE TITLE
No preview of path to cut .nc files

### ISSUE THREAD

**Issue by PederSmart** [WebControlCNC/WebControl#87]
First of all, I am very impressed with this WebControl!!

I'm on the latest version 0920 on a RPI3 and everything is working (love the camera function)
but compare to the old GroundControl I don't see the preview of what my Maslow is about to cut on the board when I open .nc files.
Could be that I am doing something wrong.

Anyway Great project!!
![NoPreviewNC](https://user-images.githubusercontent.com/58297527/73120572-b5fb6b80-3f78-11ea-87ac-191f32f58bd0.jpg)

**Comment by madgrizzle** [comment]
It doesn't look like you have a gcode file loaded.  Maybe something is wrong with the NC file that causes WebControl to error out.  Can you email it to madgrizzlemaslow at gmail dot com?

**Comment by madgrizzle** [comment]
The file you sent me didn't have the nc extension, but it doesn't really matter..

I am able to open the file fine and preview it.

![image](https://user-images.githubusercontent.com/5055291/73121612-d6600180-3f49-11ea-9a91-ac1a8c243ace.png)


I assumed you uploaded the file, correct (GCode->Upload)?  If you could, look at the terminal screen the python app is running in and see if there are any error messages that pop up after you tell it to upload.

**Comment by PederSmart** [comment]
I apologize for creating this case. It is working now for me also. You may close this case.  

Again a Great prosject!!!

**Comment by madgrizzle** [comment]
No problem..
