### ISSUE TITLE
Z axis tabs cause distortions in the GCode cut pattern

### ISSUE THREAD

**Issue by amantalion** [WebControlCNC/WebControl#89]
Hi,

I have a problem with Z axis tabs when I load them in WebControl: Z axis tabs cause distortion in the cut pattern in WebControl. When I run Maslow, then I believe distortions are also present in the contour of the final part. The same GCode is loaded properly in GroundControl. Please, see screenshots below to understand what I mean (distortions are within green circles on the WebControl screenshot).

Tabs in the CAD model:

<img width="647" alt="Screen Shot 2020-01-26 at 1 16 17 AM" src="https://user-images.githubusercontent.com/59008704/73133135-83ce2600-3fd9-11ea-8daa-2c6c3d283f86.png">

WebControl:

<img width="647" alt="Screen Shot 2020-01-26 at 1 04 11 AM" src="https://user-images.githubusercontent.com/59008704/73133077-a875ce00-3fd8-11ea-8317-9991419adbe7.png">

GroundControl:

<img width="647" alt="Screen Shot 2020-01-26 at 1 05 00 AM" src="https://user-images.githubusercontent.com/59008704/73133080-af044580-3fd8-11ea-9f78-fc79b8926a2a.png">

Final shape:
![IMG_5418](https://user-images.githubusercontent.com/59008704/73133116-2df97e00-3fd9-11ea-8cf0-fb912119d48a.jpg)

Has anyone encountered the same issue before?

**Comment by madgrizzle** [comment]
Webcontrol uses a 3d display of the gcode.  What you are seeing is the perspective of the view.   I'm fairly confident that any issues with the cut are not related to webcontrol.  Note that it looks like you are trying to make a full depth cut.. I think that you might be pushing the capability of the Maslow.  Most people would run multiple passes to get all the way through.

**Comment by madgrizzle** [comment]
I rotated the display so you can see.

![image](https://user-images.githubusercontent.com/5055291/73135967-987cdf00-4016-11ea-84f6-1600322440b0.png)

It looks like you are cutting down 14 mm (little over 1/2-inch).  That's very deep and it would explain the issues on the right side of the cut.  Rule of thumb is each pass should use a depth of cut equal to 50% the width of the router bit (it's just a rule of thumb.. I tend to not be so conservative and do maybe 80% the width of the bit).

**Comment by amantalion** [comment]
@madgrizzle Thank you! Having multiple passes resolved it: I used 80% of the end mill diameter for depth (5mm depth for the 0.25" bit).

However, I've encountered another problem: the width of the square is off by 1/16" (3.9375", instead of 4"). The diameter of the circle is off by ~1/30" (3.5" instead 3.465"). Have you seen this issue before by any chance? Do you think it's a standard error for Maslow?

I have done the Holey calibration 3 times to make sure that it's not due to the calibration.

**Comment by madgrizzle** [comment]
That's actually pretty good performance for a Maslow.  Are width and height measurements the same?

**Comment by amantalion** [comment]
Yes, width and height measurements are the same for the square.

**Comment by madgrizzle** [comment]
Then I think you're pretty well calibrated.  I'd suggest that if you need more accuracy, to tweak your CAD design (make the shapes larger or smaller as needed to get things to come out precisely as you want them).. but 1/16-inch is good.. and 1/30-inch is really good.
