### ISSUE TITLE
Webcontrol travel direction opposite.

### ISSUE THREAD

**Issue by kevinwinsor** [WebControlCNC/WebControl#99]
Started using Webcontrol today. Keypad direction keys send the sled in opposite direction from indicated. Up arrow moves the sled down, all others do the opposite as well. Same thing happens when cutting. Any ideas?

**Comment by madgrizzle** [comment]
Make sure you have the chain configuration set correctly... Advanced Settings->Top/Bottom Chain Feed

**Comment by madgrizzle** [comment]
Closed due to lack of activity
